#!/usr/bin/env php
<?php
/**
 * PhpIniSetter.
 *
 * @copyright Copyright (c) 2016 Felix Sandström
 * @license   MIT
 */
foreach (array(__DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php') as $file) {
    if (file_exists($file)) {
        require $file;

        break;
    }
}

use PhpIniSetter\PhpIniSetter;
use Symfony\Component\Console\Application;

$application = new Application('phpIniSetter');
$application->add(new PhpIniSetter());
$application->run();
